---
stages:
  - "pre-release"
  - "build"
  - "release"
  - "migrate"

include:
  - local: '.gitlab-ci/release.yml'
  - local: '.gitlab-ci/build.yml'
  - project: 'artem-shestakov/pipeline-template'
    file: github_mirror.yml
    ref: master